export const SITE_URL = 'https://neetell.in';
export const SITE_NAME = 'Neetell';
export const SITE_LOGO = `${SITE_URL}/logo-outline.png`;
export const OG_ONE = `${SITE_URL}/og-one.png`;
export const OG_TWO = `${SITE_URL}/og-two.png`;

export const socialProfileUrls = [
  'https://www.instagram.com/neetell/',
  'https://www.facebook.com/NEETell/',
  'https://neetellblog.quora.com/',
  'https://x.com/NEETell_India',
];

export const siteDescription =
  "Neetell helps NEET aspirants predict colleges, analyze cutoffs, compare MBBS fees, explore seat matrix, and make smarter AIQ & state counselling decisions.";
  
export const seoKeywords = [
  "Neetell",
  "NEET",
  "NEET 2026",
  "NEET UG",
  "NEET PG",
  "NEET counselling",
  "NEET UG counselling",
  "NEET PG counselling",
  "NEET counselling 2026",
  "NEET admission",
  "medical admission",
  "MBBS admission",
  "BDS admission",
  "BAMS admission",
  "BHMS admission",
  "BUMS admission",
  "BVSc admission",
  "medical counselling",
  "online counselling",
  "medical college admission",

  "NEET college predictor",
  "NEET rank predictor",
  "NEET score predictor",
  "medical college predictor",
  "MBBS college predictor",
  "BDS college predictor",
  "government college predictor",
  "private college predictor",
  "AIQ college predictor",
  "state quota college predictor",

  "NEET cutoff",
  "NEET cutoff 2026",
  "expected NEET cutoff",
  "previous year NEET cutoff",
  "NEET qualifying marks",
  "category wise cutoff",
  "general cutoff",
  "OBC cutoff",
  "SC cutoff",
  "ST cutoff",
  "EWS cutoff",
  "PWD cutoff",
  "AIIMS cutoff",
  "JIPMER cutoff",
  "government college cutoff",
  "private college cutoff",
  "closing rank",
  "opening rank",
  "last rank",
  "safe score",

  "NEET rank",
  "AIR rank",
  "expected rank",
  "marks vs rank",
  "rank vs college",
  "rank wise colleges",
  "score vs rank",
  "college by rank",

  "NEET seat matrix",
  "MBBS seat matrix",
  "AIQ seat matrix",
  "state quota seat matrix",
  "college wise seats",
  "category wise seats",
  "medical seats India",
  "MBBS seats",
  "government MBBS seats",
  "private MBBS seats",

  "MCC counselling",
  "DGHS counselling",
  "AIQ counselling",
  "state quota counselling",
  "15% AIQ counselling",
  "85% state quota",
  "MCC registration",
  "choice filling",
  "choice locking",
  "seat allotment",
  "mop up round",
  "stray vacancy",
  "upgrade option",
  "freeze option",
  "reporting process",

  "medical college fees",
  "MBBS fees",
  "government MBBS fees",
  "private MBBS fees",
  "deemed university fees",
  "AIIMS fees",
  "JIPMER fees",
  "hostel fees",
  "tuition fees",
  "NRI quota fees",
  "management quota fees",
  "medical bond",
  "service bond",
  "bond amount",
  "bond colleges",

  "government medical colleges",
  "private medical colleges",
  "deemed medical colleges",
  "best medical colleges",
  "top medical colleges India",
  "medical colleges by state",
  "AIIMS colleges",
  "JIPMER colleges",
  "ESIC colleges",
  "central universities",
  "new medical colleges",

  "UP NEET counselling",
  "Bihar NEET counselling",
  "Rajasthan NEET counselling",
  "Maharashtra NEET counselling",
  "Karnataka NEET counselling",
  "Tamil Nadu NEET counselling",
  "Kerala NEET counselling",
  "Gujarat NEET counselling",
  "West Bengal NEET counselling",
  "Punjab NEET counselling",
  "Haryana NEET counselling",
  "Delhi NEET counselling",
  "Madhya Pradesh NEET counselling",
  "Chhattisgarh NEET counselling",
  "Odisha NEET counselling",
  "Assam NEET counselling",
  "Jharkhand NEET counselling",
  "Telangana NEET counselling",
  "Andhra Pradesh NEET counselling",
  "Uttarakhand NEET counselling",
  "Himachal Pradesh NEET counselling",
  "Goa NEET counselling",
  "Jammu Kashmir NEET counselling",

  "AIIMS Delhi cutoff",
  "AIIMS Bhopal cutoff",
  "AIIMS Jodhpur cutoff",
  "AIIMS Rishikesh cutoff",
  "AIIMS Patna cutoff",
  "AIIMS Raipur cutoff",
  "AIIMS Bhubaneswar cutoff",
  "AIIMS Nagpur cutoff",
  "AIIMS Kalyani cutoff",
  "JIPMER Puducherry cutoff",

  "medical college list",
  "government MBBS colleges",
  "private MBBS colleges",
  "deemed universities",
  "medical colleges in UP",
  "medical colleges in Bihar",
  "medical colleges in Rajasthan",
  "medical colleges in Maharashtra",
  "medical colleges in Karnataka",
  "medical colleges in Tamil Nadu",

  "MBBS admission 2026",
  "medical admission 2026",
  "NEET registration",
  "NTA NEET",
  "NMC colleges",
  "NMC approved colleges",
  "MCC seat allotment",
  "choice filling strategy",
  "best choice filling order",
  "college preference list",
  "MBBS counselling guide",
  "medical admission guide",

  "MBBS government colleges",
  "MBBS private colleges",
  "BDS counselling",
  "AYUSH counselling",
  "BAMS counselling",
  "BHMS counselling",
  "BUMS counselling",
  "BVSc counselling",

  "medical college ranking",
  "medical college comparison",
  "college finder",
  "college search",
  "college recommendation",
  "medical college reviews",

  "NEET marks calculator",
  "NEET percentile",
  "expected percentile",
  "marks predictor",
  "rank estimator",

  "NEET latest news",
  "NEET updates",
  "NTA updates",
  "NEET notification",
  "MCC notification",
  "counselling schedule",
  "registration dates",
  "important dates",

  "MBBS admission India",
  "medical entrance",
  "doctor admission",
  "MBBS counselling",
  "medical education India",
  "medical colleges India",
  "medical seat allotment",
  "college allotment",
  "all India quota",
  "state quota",
  "medical counselling portal",

  "Neetell college predictor",
  "Neetell rank predictor",
  "Neetell counselling",
  "Neetell cutoff",
  "Neetell seat matrix",
  "Neetell choice filling",
  "Neetell MBBS predictor",
  "Neetell AIQ predictor",
  "Neetell state quota predictor",
  "Neetell medical colleges",
  "Neetell fees",
  "Neetell bond",
  "Neetell counselling guide",
  "Neetell medical admission",
  "Neetell MBBS admission",
  "Neetell NEET tools",
  "Neetell NEET predictor",
  "Neetell rank calculator",
  "Neetell score predictor",
  "Neetell counselling platform",
  "AIIMS New Delhi",
  "AIIMS Bhopal",
  "AIIMS Bhubaneswar",
  "AIIMS Jodhpur",
  "AIIMS Patna",
  "AIIMS Raipur",
  "AIIMS Rishikesh",
  "AIIMS Nagpur",
  "AIIMS Kalyani",
  "AIIMS Gorakhpur",
  "AIIMS Rae Bareli",
  "AIIMS Deoghar",
  "AIIMS Bibinagar",
  "AIIMS Mangalagiri",
  "AIIMS Bathinda",
  "AIIMS Bilaspur",
  "AIIMS Guwahati",
  "AIIMS Jammu",
  "AIIMS Madurai",
  "AIIMS Rajkot",
  "AIIMS Vijaypur",
  "JIPMER Puducherry",
  "JIPMER Karaikal",
  "King George's Medical University",
  "Institute of Medical Sciences BHU",
  "Maulana Azad Medical College",
  "Lady Hardinge Medical College",
  "University College of Medical Sciences",
  "Vardhman Mahavir Medical College",
  "Safdarjung Hospital Medical College",
  "Atal Bihari Vajpayee Institute of Medical Sciences",
  "Dr Ram Manohar Lohia Medical College",
  "Government Medical College Chandigarh",
  "Government Medical College Amritsar",
  "Government Medical College Patiala",
  "Government Medical College Jammu",
  "Government Medical College Srinagar",
  "Government Medical College Baramulla",
  "Government Medical College Doda",
  "Government Medical College Kathua",
  "Government Medical College Rajouri",
  "Government Medical College Anantnag",
  "SMS Medical College Jaipur",
  "RUHS Medical College Jaipur",
  "Jhalawar Medical College",
  "RNT Medical College Udaipur",
  "SP Medical College Bikaner",
  "JN Medical College Ajmer",
  "Government Medical College Kota",
  "Dr SN Medical College Jodhpur",
  "Government Medical College Bharatpur",
  "Government Medical College Dungarpur",
  "Government Medical College Pali",
  "Government Medical College Churu",
  "Government Medical College Sirohi",
  "Government Medical College Barmer",
  "Government Medical College Bhilwara",
  "Government Medical College Dausa",
  "Government Medical College Hanumangarh",
  "Government Medical College Alwar",
  "Seth GS Medical College Mumbai",
  "Grant Medical College Mumbai",
  "BJ Government Medical College Pune",
  "Government Medical College Nagpur",
  "Government Medical College Aurangabad",
  "Government Medical College Akola",
  "Government Medical College Latur",
  "Government Medical College Miraj",
  "Government Medical College Gondia",
  "Government Medical College Jalgaon",
  "Government Medical College Chandrapur",
  "Government Medical College Nanded",
  "Government Medical College Baramati",
  "Government Medical College Dhule",
  "Government Medical College Kolhapur",
  "Government Medical College Yavatmal",
  "Madras Medical College",
  "Stanley Medical College",
  "Kilpauk Medical College",
  "Chengalpattu Medical College",
  "Coimbatore Medical College",
  "Government Mohan Kumaramangalam Medical College",
  "Madurai Medical College",
  "Thanjavur Medical College",
  "Tirunelveli Medical College",
  "Government Medical College Omandurar",
  "Government Villupuram Medical College",
  "Government Erode Medical College",
  "Government Dharmapuri Medical College",
  "Government Sivagangai Medical College",
  "Government Medical College Dindigul",
  "Bangalore Medical College",
  "Mysore Medical College",
  "Belagavi Institute of Medical Sciences",
  "Shimoga Institute of Medical Sciences",
  "Bidar Institute of Medical Sciences",
  "Gulbarga Institute of Medical Sciences",
  "Hassan Institute of Medical Sciences",
  "Mandya Institute of Medical Sciences",
  "Raichur Institute of Medical Sciences",
  "Kodagu Institute of Medical Sciences",
  "ESIC Medical College Bangalore",
  "Osmania Medical College",
  "Gandhi Medical College Hyderabad",
  "Kakatiya Medical College",
  "Government Medical College Nizamabad",
  "Government Medical College Mahabubnagar",
  "Government Medical College Siddipet",
  "Government Medical College Suryapet",
  "Government Medical College Nalgonda",
  "Andhra Medical College",
  "Guntur Medical College",
  "Kurnool Medical College",
  "Siddhartha Medical College",
  "Rangaraya Medical College",
  "Government Medical College Anantapur",
  "Government Medical College Eluru",
  "Government Medical College Vizianagaram",
  "Government Medical College Rajamahendravaram",
  "Medical College Kolkata",
  "RG Kar Medical College",
  "NRS Medical College",
  "IPGMER Kolkata",
  "Bankura Sammilani Medical College",
  "Burdwan Medical College",
  "North Bengal Medical College",
  "Malda Medical College",
  "Murshidabad Medical College",
  "Midnapore Medical College",
  "Nil Ratan Sircar Medical College",
  "Calcutta National Medical College",
  "Medical College Thiruvananthapuram",
  "Government Medical College Kozhikode",
  "Government Medical College Kottayam",
  "Government Medical College Thrissur",
  "Government Medical College Kannur",
  "Government Medical College Ernakulam",
  "Government Medical College Manjeri",
  "Government Medical College Palakkad",
  "Government Medical College Alappuzha",
  "Government Medical College Kollam",
  "BJ Medical College Ahmedabad",
  "Government Medical College Surat",
  "Government Medical College Bhavnagar",
  "Government Medical College Rajkot",
  "Government Medical College Baroda",
  "GMERS Medical College Gandhinagar",
  "GMERS Medical College Sola",
  "GMERS Medical College Himmatnagar",
  "Government Medical College Patan",
  "SCB Medical College Cuttack",
  "MKCG Medical College Berhampur",
  "Government Medical College Balasore",
  "Government Medical College Koraput",
  "Government Medical College Sundargarh",
  "VIMSAR Burla",
  "Patna Medical College",
  "Nalanda Medical College",
  "Darbhanga Medical College",
  "Jawaharlal Nehru Medical College Bhagalpur",
  "Government Medical College Bettiah",
  "Indira Gandhi Institute of Medical Sciences",
  "Government Medical College Purnea",
  "Government Medical College Madhepura",
  "Rajendra Institute of Medical Sciences",
  "MGM Medical College Jamshedpur",
  "Shaheed Nirmal Mahto Medical College",
  "Government Medical College Hazaribagh",
  "Government Medical College Dumka",
  "Government Medical College Palamu",
  "Government Medical College Dhanbad",
  "Gajra Raja Medical College",
  "Gandhi Medical College Bhopal",
  "Netaji Subhash Chandra Bose Medical College",
  "MGM Medical College Indore",
  "Government Medical College Ratlam",
  "Government Medical College Vidisha",
  "Government Medical College Datia",
  "Government Medical College Khandwa",
  "Pt JNM Medical College Raipur",
  "Government Medical College Bilaspur",
  "Government Medical College Jagdalpur",
  "Government Medical College Rajnandgaon",
  "Government Medical College Ambikapur",
  "Government Medical College Korba",
  "Government Medical College Raigarh",
  "Government Medical College Durg",
  "Government Doon Medical College",
  "Government Medical College Haldwani",
  "Government Medical College Almora",
  "Government Medical College Srinagar Uttarakhand",
  "Indira Gandhi Medical College Shimla",
  "Dr RPG Medical College Tanda",
  "Government Medical College Nahan",
  "Government Medical College Hamirpur",
  "Government Medical College Chamba",
  "Goa Medical College",
  "Agartala Government Medical College",
  "Regional Institute of Medical Sciences Imphal",
  "North Eastern Indira Gandhi Regional Institute of Health and Medical Sciences",
  "Fakhruddin Ali Ahmed Medical College",
  "Assam Medical College",
  "Gauhati Medical College",
  "Silchar Medical College",
  "Jorhat Medical College",
  "Tezpur Medical College",
  "Diphu Medical College",
  "Lakhimpur Medical College",
  "Tripura Medical College",
  "Sikkim Manipal Institute of Medical Sciences",
  "Government Medical College Nagaland",
  "Government Medical College Arunachal Pradesh",
  "Christian Medical College Vellore",
  "Kasturba Medical College Manipal",
  "Kasturba Medical College Mangalore",
  "St John's Medical College",
  "Jamia Hamdard Medical College",
  "Hamdard Institute of Medical Sciences",
  "Amrita Institute of Medical Sciences",
  "Sri Ramachandra Medical College",
  "Saveetha Medical College",
  "SRM Medical College",
  "KIMS Bhubaneswar",
  "DY Patil Medical College Pune",
  "DY Patil Medical College Navi Mumbai",
  "MGM Medical College Navi Mumbai",
  "Bharati Vidyapeeth Medical College Pune"
];

export const faqItems = [
  {
    question: 'What is Neetell?',
    answer:
      'Neetell is a NEET counselling intelligence platform that helps students explore medical colleges, compare fees and bonds, study cutoff trends, and plan AIQ and state counselling choices.',
  },
  {
    question: 'Does Neetell help with NEET UG and NEET PG counselling?',
    answer:
      'Neetell is built for NEET counselling workflows, including college discovery, cutoff analysis, rank-aware prediction, choice filling, and counselling guidance for medical admissions.',
  },
  {
    question: 'Can I find medical colleges based on my NEET rank?',
    answer:
      'Yes. Neetell includes rank-aware tools to help students identify realistic safe, target, and dream college options using historical cutoff and counselling data.',
  },
  {
    question: 'What data can I compare for medical colleges?',
    answer:
      'You can compare key decision factors such as fees, seat matrix, cutoff trends, bond requirements, college type, state, quota, and other counselling parameters.',
  },
  {
    question: 'Is Neetell a replacement for official counselling websites?',
    answer:
      'No. Neetell helps students understand and plan counselling decisions, but students should always verify final dates, eligibility, allotments, and notices on official counselling authority websites.',
  },
];

export const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: SITE_NAME,
  url: SITE_URL,
  logo: SITE_LOGO,
  email: 'support@neetell.in',
  description: siteDescription,
  sameAs: socialProfileUrls,
};

export const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: SITE_NAME,
  url: SITE_URL,
  description: siteDescription,
  applicationName: SITE_NAME,
  inLanguage: 'en',
  potentialAction: {
    '@type': 'SearchAction',
    target: `${SITE_URL}/dashboard/colleges?q={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
};

export const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqItems.map(item => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: {
      '@type': 'Answer',
      text: item.answer,
    },
  })),
};

export const courseJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Course',
  name: 'NEET Counselling Guidance Program',
  description:
    'A structured counselling guidance program for NEET aspirants covering rank-based college prediction, cutoff trends, fees, bonds, seat matrix, AIQ and state counselling, and choice filling strategy.',
  provider: {
    '@type': 'Organization',
    name: SITE_NAME,
    sameAs: SITE_URL,
  },
  educationalLevel: 'Medical entrance counselling',
  audience: {
    '@type': 'EducationalAudience',
    educationalRole: 'student',
  },
};

export const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: SITE_URL,
    },
  ],
};

export const softwareAppSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Neetell",
  applicationCategory: "EducationalApplication",
  operatingSystem: "iOS, Android, Web",
  url: SITE_URL,
  offers: [
    {
      "@type": "Offer",
      name: "NEET UG Plan",
      price: "3999",
      priceCurrency: "INR",
      description: "Full NEET UG counselling tools valid through final round",
    },
    {
      "@type": "Offer",
      name: "NEET PG Plan",
      price: "3999",
      priceCurrency: "INR",
      description: "Full NEET PG counselling tools including DNB support, valid 1 year",
    },
    {
      "@type": "Offer",
      name: "INI-CET Plan",
      price: "999",
      priceCurrency: "INR",
      description: "INI-CET college predictor and AIIMS/central institute data",
    },
  ],
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.8",
    reviewCount: "27000",
  },
};


const ratingValue = process.env.NEXT_PUBLIC_SCHEMA_RATING_VALUE || '4.8';
const reviewCount = process.env.NEXT_PUBLIC_SCHEMA_REVIEW_COUNT || '27000';

export const reviewJsonLd =
  ratingValue && reviewCount
    ? {
        '@context': 'https://schema.org',
        '@type': 'Service',
        name: 'Neetell NEET Counselling Guidance',
        serviceType: 'NEET counselling guidance and college prediction',
        provider: {
          '@type': 'Organization',
          name: SITE_NAME,
          url: SITE_URL,
        },
        areaServed: {
          '@type': 'Country',
          name: 'India',
        },
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue,
          reviewCount,
          bestRating: '5',
          worstRating: '1',
        },
      }
    : null;

export const rootJsonLd = [
  organizationJsonLd,
  websiteJsonLd,
  faqJsonLd,
  courseJsonLd,
  breadcrumbJsonLd,
  softwareAppSchema,
  ...(reviewJsonLd ? [reviewJsonLd] : []),
];
